// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCljFYrt0L8QneNvWwXMkiQ41byulvbPO0',
    appId: '1:312906007506:web:237fd44efc0bee68effe0b',
    messagingSenderId: '312906007506',
    projectId: 'kkumool-dart',
    authDomain: 'kkumool-dart.firebaseapp.com',
    storageBucket: 'kkumool-dart.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDaUwcHHJQEPioYYRTt4UzMXznyG6SeYVk',
    appId: '1:312906007506:android:6085a5eda40d8219effe0b',
    messagingSenderId: '312906007506',
    projectId: 'kkumool-dart',
    storageBucket: 'kkumool-dart.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-tvBbBDgHuCEdX1ijP7KmtzkSXgPHIYw',
    appId: '1:312906007506:ios:c516e2caea332dc4effe0b',
    messagingSenderId: '312906007506',
    projectId: 'kkumool-dart',
    storageBucket: 'kkumool-dart.appspot.com',
    iosBundleId: 'com.kkumool.back',
  );
}
